name: CMake Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          - version: "14"

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: "3.22.x"

      - name: CMake Build
        run: cmake -S ./ -B ./build